import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MainProviders } from '../providers/main-providers';
import './globals.css';
import Header from '@/components/Header';
import { Footer } from '@/components/Footer';
import ReduxProvider from '@/redux/redux-provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header />
          {children}
          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            closeOnClick
            draggable
          />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
