import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MainProviders } from '../providers/main-providers';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className="h-full">
      <head />
      <body className="flex flex-col">
        <MainProviders>{children}</MainProviders>
      </body>
    </html>
  );
}
